# Generated by Django 4.2.3 on 2023-07-12 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('boy_rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2)])),
                ('girl_rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2)])),
                ('name_variants', models.JSONField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('African', 'African'), ('Asian', 'Asian'), ('Caucasian', 'Caucasian'), ('Hispanic', 'Hispanic'), ('Middle Eastern', 'Middle Eastern'), ('Native American', 'Native American'), ('Pacific Islander', 'Pacific Islander'), ('Two or More Races', 'Two Or More Races'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Secular', 'Secular'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Bahai', 'Bahai'), ('Jainism', 'Jainism'), ('Shinto', 'Shinto')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamousPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('wikipedia_link', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.babyname')),
            ],
        ),
        migrations.CreateModel(
            name='NameStateRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.babyname')),
            ],
            options={
                'unique_together': {('name', 'gender', 'year', 'state')},
            },
        ),
        migrations.CreateModel(
            name='NameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.babyname')),
            ],
            options={
                'unique_together': {('name', 'gender', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BabyNameRef',
            fields=[
                ('babyname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.babyname')),
                ('famous_people_list', models.ManyToManyField(blank=True, related_name='baby_names', to='app.famousperson')),
            ],
            bases=('app.babyname',),
        ),
    ]
