# Generated by Django 4.2.3 on 2023-07-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_famousperson_id_famousperson_related_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famousperson',
            old_name='related_name',
            new_name='first_name',
        ),
    ]
