# Generated by Django 4.2.3 on 2023-07-19 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyname',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
