# Generated by Django 4.2.3 on 2023-07-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_babytags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyname',
            name='ethnicity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='language',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='region',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyname',
            name='religion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
