# Generated by Django 4.2.3 on 2023-07-24 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_babyname_author_babyname_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyname',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='babyname',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
