# Generated by Django 4.2.3 on 2023-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_babyname_author_babyname_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousperson',
            name='popularity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
